/**
 * Created by Jebin for iLeaf Solutions Pvt.Ltd
 * on February 12, 2020
 * Action Types - differnt action types used.
 */

// app
export const APP_NETWORK_STATUS = 'APP_NETWORK_STATUS';
export const APP_LANGUAGE_CHANGE = 'APP_LANGUAGE_CHANGE';
export const APP_STORE_CODE_CHANGE = 'APP_STORE_CODE_CHANGE';
export const ORIENTATION_CHANGE = 'ORIENTATION_CHANGE';
export const UPDATE_STORES_INFO = 'UPDATE_STORES_INFO';
export const UPDATE_FILTER_DATAS = 'UPDATE_FILTER_DATAS';
export const APP_UPDATE_USER_INFO = 'APP_UPDATE_USER_INFO';
export const APP_UPDATE_CURRENCY = 'APP_UPDATE_CURRENCY';
export const UPDATE_DEVICE_TYPE = 'UPDATE_DEVICE_TYPE';

//loaders
export const ENABLE_LOADER = 'ENABLE_LOADER';
export const DISABLE_LOADER = 'DISABLE_LOADER';
export const PRODUCT_LIST_ENABLE_LOADER = 'PRODUCT_LIST_ENABLE_LOADER';
export const PRODUCT_LIST_DISABLE_LOADER = 'PRODUCT_LIST_DISABLE_LOADER';

// login
export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_RESPONSE = 'LOGIN_RESPONSE';
export const LOGIN_FAILED = 'LOGIN_FAILED';
export const PROFILE_UPDATE_REQUEST = 'PROFILE_UPDATE_REQUEST';
export const PROFILE_UPDATE_RESPONSE = 'PROFILE_UPDATE_RESPONSE';
export const USER_WISHLIST_RESPONSE = 'USER_WISHLIST_RESPONSE';
export const REMOVE_WISHLIST_ITEM = 'REMOVE_WISHLIST_ITEM';
export const ADD_WISHLIST_ITEM = 'ADD_WISHLIST_ITEM';
export const USER_LOG_OUT = 'USER_LOG_OUT';
export const GUEST_CART_CLEAR = 'GUEST_CART_CLEAR';
export const UPDATE_GUEST_INFO = 'UPDATE_GUEST_INFO';
export const SUBMIT_CONTACT_US = 'SUBMIT_CONTACT_US';

// guest
export const CREATE_GUEST_CART = 'CREATE_GUEST_CART';
export const UPDATE_GUEST_TOKEN = 'UPDATE_GUEST_TOKEN';
export const GUEST_ADD_TO_CART = 'GUEST_ADD_TO_CART';
export const CLEAR_QUOTE_ID = 'CLEAR_QUOTE_ID';

// cart
export const UPDATE_CART_LIST = 'UPDATE_CART_LIST';

// register
export const REGISTER_REQUEST = 'REGISTER_REQUEST';
export const REGISTER_RESPONSE = 'REGISTER_RESPONSE';
export const REGISTER_FAILED = 'REGISTER_FAILED';

// country selection
export const GET_STORES = 'GET_STORES';
export const GET_STORES_VIEW = 'GET_STORES_VIEW';
export const GET_STORES_RESPONSE = 'GET_STORES_RESPONSE';

// search
export const SEARCH_TEXT_CHANGE = 'SEARCH_TEXT_CHANGE';
export const UPDATE_SEARCH_HISTORY = 'UPDATE_SEARCH_HISTORY';
export const UPDATE_SEARCH_RESULT = 'UPDATE_SEARCH_RESULT';
export const CLEAR_SEARCH_RESULT = 'CLEAR_SEARCH_RESULT';

// categories
export const GET_ALL_CATEGORIES = 'GET_ALL_CATEGORIES';
export const GET_ALL_CATEGORIES_RESPONSE = 'GET_ALL_CATEGORIES_RESPONSE';
export const GET_ALL_CATEGORIES_FAILURE = 'GET_ALL_CATEGORIES_FAILURE';

//add address
export const ADD_ADDRESS_REQUEST = 'ADD_ADDRESS_REQUEST';
export const ADD_ADDRESS_RESPONSE = 'ADD_ADDRESS_RESPONSE';
export const ADD_ADDRESS_FAILED = 'ADD_ADDRESS_FAILED';

// edit address
export const EDIT_ADDRESS_REQUEST = 'EDIT_ADDRESS_REQUEST';
export const EDIT_ADDRESS_RESPONSE = 'EDIT_ADDRESS_RESPONSE';
export const EDIT_ADDRESS_FAILED = 'EDIT_ADDRESS_FAILED';
export const UPDATE_ADDRESS = 'UPDATE_ADDRESS';
export const DELETE_ADDRESS = 'DELETE_ADDRESS';

// products
export const GET_PRODUCTS_LIST = 'GET_PRODUCTS_LIST';
export const GET_PRODUCT_DETAIL = 'GET_PRODUCT_DETAIL';
export const UPDATE_PRODUCTS_LIST = 'UPDATE_PRODUCTS_LIST';
export const UPDATE_PRODUCT_DETAIL = 'UPDATE_PRODUCT_DETAIL';
export const GET_ROTTATION_IMGAGES_ARRAY = 'GET_ROTTATION_IMGAGES_ARRAY';

//filter response
export const FILTER_REQUEST = 'FILTER_REQUEST';
export const FILTER_RESPONSE = 'FILTER_RESPONSE';
export const FILTER_FAILURE = 'FILTER_FAILURE';

//filter page
export const LOAD_FILTER_REQUEST = 'LOAD_FILTER_REQUEST';
export const LOAD_FILTER_RESPONSE = 'LOAD_FILTER_RESPONSE';
export const LOAD_FILTER_FAILURE = 'LOAD_FILTER_FAILURE';
export const UPDATE_SELECTED_FILTERS = 'UPDATE_SELECTED_FILTERS';
export const RESET_FILTER = 'RESET_FILTER';
export const RESET_FILTER_DATA = 'RESET_FILTER_DATA';

//home category list
export const GET_CATEGORY_PRODUCTS_LIST = 'GET_CATEGORY_PRODUCTS_LIST';
export const CLEAR_CATEGORY_PRODUCTS_LIST = 'CLEAR_CATEGORY_PRODUCTS_LIST';
export const UPDATE_CATEGORY_PRODUCTS_LIST = 'UPDATE_CATEGORY_PRODUCTS_LIST';

//category product list
// export const GET_CATEGORY_PRODUCTS_LIST_FROM_CATEGORY = 'GET_CATEGORY_PRODUCTS_LIST_FROM_CATEGORY';
export const CLEAR_CATEGORY_PRODUCTS_LIST_FROM_CATEGORY =
  'CLEAR_CATEGORY_PRODUCTS_LIST_FROM_CATEGORY';
export const UPDATE_CATEGORY_PRODUCTS_LIST_FROM_CATEGORY =
  'UPDATE_CATEGORY_PRODUCTS_LIST_FROM_CATEGORY';

//home page
export const GET_HOME_REQUEST = 'GET_HOME_REQUEST';
export const GET_HOME_RESPONSE = 'GET_HOME_RESPONSE';
export const GET_HOME_FAILED = 'GET_HOME_FAILED';

//cart
export const GET_PRODUCTS_IN_CART = 'GET_PRODUCTS_IN_CART';
export const CART_PRODUCT_LIST = 'CART_PRODUCT_LIST';
export const GET_PRODUCTS_IN_CART_FAILED = 'GET_PRODUCTS_IN_CART_FAILED';
export const REMOVE_PRODUCT_FROM_CART = 'REMOVE_PRODUCT_FROM_CART';
export const ADD_CART_PRODUCT_TO_WISHLIST = 'ADD_CART_PRODUCT_TO_WISHLIST';
export const UPADTE_CART_ID = 'UPADTE_CART_ID';
export const ADD_PRODUCT_TO_CART_LOGGEDUSER = 'ADD_PRODUCT_TO_CART_LOGGEDUSER';
export const UPDATE_CART_PRODUCT_LIST = 'UPDATE_CART_PRODUCT_LIST';
export const UPDATE_GUEST_CART_PRODUCT_LIST = 'UPDATE_GUEST_CART_PRODUCT_LIST';
export const REMOVE_GUEST_CART = 'REMOVE_GUEST_CART';
export const REMOVE_USER_CART = 'REMOVE_USER_CART';
export const UPDATE_GUEST_CART = 'UPDATE_GUEST_CART';
export const UPDATE_USER_CART = 'UPDATE_USER_CART';
export const GET_TOTAL_CART_COST = 'GET_TOTAL_CART_COST';
export const GET_LOGGED_USER_CART_ID = 'GET_LOGGED_USER_CART_ID';

//checkout
export const SET_SHIPMENT_INFO = 'SET_SHIPMENT_INFO';
export const APPLY_VOUCHER_CODE = 'APPLY_VOUCHER_CODE';
export const GET_PAYMENT_AND_SHIPPING_METHODS =
  'GET_PAYMENT_AND_SHIPPING_METHODS';
export const SET_BILLING_ADDRESS = 'SET_BILLING_ADDRESS';

//Order History
export const GET_ORDER_HISTORY = 'GET_ORDER_HISTORY';
